# Generated by Django 4.1.1 on 2022-10-04 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anotacoes', '0004_alter_anotacoes_fk_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoes',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
