# Generated by Django 4.1.1 on 2022-09-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
        ('anotacoes', '0002_alter_anotacoes_fk_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotacoes',
            old_name='mensagem',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='anotacoes',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='anotacoes',
            name='fk_grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo'),
        ),
    ]
