# Generated by Django 4.1.1 on 2022-10-10 14:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0003_alter_grupo_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('date_start', models.DateField(blank=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('fk_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grupos.grupo')),
                ('fk_pessoa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
