# Generated by Django 4.1.1 on 2022-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='date_start',
            field=models.DateField(),
        ),
    ]
