# Generated by Django 4.1.1 on 2022-10-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefas_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
