# Generated by Django 4.1.1 on 2022-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_tarefas_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
