# Generated by Django 4.1.1 on 2022-10-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_alter_grupo_fk_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
